# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Init
      run: go mod tidy

    - name: Test
      run: go test -v ./...

    - name: Coverage
      run: go test -coverprofile=coverage.txt

    - name: "Upload coverage reports to Codecov"
      uses: codecov/codecov-action@v5
      with:
        token: 910d5086-b1d9-4e08-b77b-320ade59dbbb
        slug: VarusHsu/slicesx

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1"
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --verbose
          skip-go-installation: true

